config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:new, :create, :update]
  patch '/cat_rental_requests/approve/:id' => 'cat_rental_requests#approve', :as => "approve"
  patch '/cat_rental_requests/deny/:id' => 'cat_rental_requests#deny', :as => "deny"
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ActiveRecord::Base
  CAT_COLORS = ["Brown", "Black", "White", "Spotted"]
  validates :birth_date, :color, :name, presence: true
  validates :sex, length: { in: 0..1 }, inclusion: { in: ["M", "F"],
    message: "Please pick either M or F" }
  validates :color, inclusion: { in: CAT_COLORS,
    message: "Please pick a valid color" }


  has_many :cat_rental_requests, dependent: :destroy

  def age
    now = Time.now.utc.to_date
    bday = self.birth_date
    now.year - bday.year - ((now.month > bday.month ||
    (now.month == bday.month && now.day >= bday.day)) ? 0 : 1)
  end

  


end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ActiveRecord::Base
  STATUS = %w(DENIED APPROVED PENDING)

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: STATUS, message: 'Please pick a valid status' }
  validate :overlapping_approved_requests

  belongs_to :cat

  def overlaps?(other)
    return true if self.start_date >= other.start_date && self.start_date <= other.end_date
    return true if self.end_date <= other.end_date && self.end_date >= other.start_date
    return true if self.start_date <= other.start_date && self.end_date >= other.end_date
    return false
  end

  def overlapping_approved_requests
    all_approved_requests = CatRentalRequest.where("cat_id = ? AND status = ?", self.cat_id, "APPROVED")
    all_approved_requests.each do |request|
      if self.overlaps?(request)
        self.errors[:overlap] << "This is an overlapping request"
      end
    end
  end

  def overlapping_pending_requests
    conflicts = []
    all_approved_requests = CatRentalRequest.where("cat_id = ? AND status = ?", self.cat_id, "PENDING")
    all_approved_requests.each do |request|
      if self.overlaps?(request)
        conflicts << request
      end
    end
    conflicts
  end

  def approve!
    CatRentalRequest.transaction do
      self.status = "APPROVED"
      self.save
      overlapping_pending_requests.each do |request|
        request.deny!
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save
  end

  def pending?
    self.status == 'PENDING'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(rental_params)
    if @cat_rental_request.save!
      redirect_to cat_url(rental_params[:cat_id])
    else
      render @cat_rental_request.errors.full_messages
    end
  end

  def approve
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    if @cat_rental_request.approve!
      redirect_to cat_url(@cat_rental_request[:cat_id])
    else
      render @cat_rental_request.errors.full_messages
    end
  end

  def deny
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    @cat_rental_request.deny!
    redirect_to cat_url(@cat_rental_request[:cat_id])
  end

  private
  def rental_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id, :status)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find_by(id: params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.save!
    redirect_to cat_url(@cat)
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render @cat.errors.full_messages
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>new rental_request</title>
  </head>
  <body>
    <form action="/cat_rental_requests" method="post">
      <label for="cat">Choose your cat:</label>
      <select name="cat_rental_request[cat_id]" id="cat">
        <option></option>
        <% Cat.all.each do |cat| %>
          <option value= <%= cat.id %>> <%= cat.name %>
          </option>
        <% end %>
      </select>

    <label for="start date">Start date</label>
    <input type="date" name= "cat_rental_request[start_date]" value= <%= @cat_rental_request.start_date %>>

    <label for="end date">End date</label>
    <input type="date" name= "cat_rental_request[end_date]" value= <%= @cat_rental_request.end_date %>>

      <input type="submit" value="Choose Cat">
    </form>

  </body>
</html>

app/views/cats/_form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>edit view</title>
  </head>
  <body>
    <% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
    <form action= <%= action_url %> method="post">
      <% if cat.persisted? %>
        <input type="hidden" name="_method" value="patch">
      <% end %>
      <label for="name">Cat's Name:</label>
      <input id="name" type="text" name="cat[name]" value= <%= cat.name %>>

      <label for="sex">Cat's Sex:</label>
      F <input type="radio" name="cat[sex]" value="F" <%= cat.sex == 'F' ? "checked" : '' %>>
      M <input type="radio" name="cat[sex]" value="M" <%= cat.sex == 'M' ? "checked" : '' %>>

      <label for="color">Cat's color</label>
      <select name="cat[color]" id="color">
        <option></option>
        <% Cat::CAT_COLORS.each do |color| %>
          <option value= <%= color %>
          <%= cat.color == color ? "selected" : "" %>> <%= color %>
          </option>
        <% end %>
      </select>

      <label for="birth date">Cat's birth date</label>
      <input type="date" name= "cat[birth_date]" value= <%= cat.birth_date %>>
      </br>
      <label for="description">Cat's description</label>
      <textarea id="description" name="cat[description]" rows="8" cols="40"><%= cat.description %></textarea>

      <input type="submit" value="Edit Cat">
    </form>

  </body>
</html>

app/views/cats/edit.html.erb
<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>All of our cats</title>
  </head>
  <body>
    <h1>All of our beautiful cats</h1>
    <ul>
      <% @cats.each do |cat| %>
        <li>
          <%= link_to cat.name, cat_url(cat) %>
        </li>
      <% end %>
    </ul>
  <h3><%= link_to "make a new cat", new_cat_url %></h3>
  </body>
</html>

app/views/cats/new.html.erb
<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>An amazing cat</title>
  </head>
  <body>
    <h1><%= @cat.name %></h1>
    <table border=2 >
      <tr>
        <th> Birth Date </th>
        <th> Age </th>
        <th> Sex </th>
        <th> Color </th>
      </tr>
      <tr>
        <td> <%= @cat.birth_date  %> </td>
        <td> <%= @cat.age  %> </td>
        <td> <%= @cat.sex  %> </td>
        <td> <%= @cat.color  %> </td>
      </tr>
    </table>
    <p>
      About me: <%= @cat.description %>
    </p>
    <table border=2 >
      <h2>Rental requests</h2>
      <tr>
        <th> Start date </th>
        <th> End date </th>
        <th> Status </th>
        <th> Approve/Deny </th>
      </tr>
    <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
      <tr>
        <td> <%= request.start_date %> </td>
        <td> <%= request.end_date %> </td>
        <td> <%= request.status  %> </td>
        <td>
          <% if request.pending? %>
          <%= button_to 'Approve', approve_url(request), method: :patch %>
          <%= button_to 'Deny', deny_url(request), method: :patch %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
    <h3><%= link_to "index", cats_url %></h3>
    <h3><%= link_to "request new cat", new_cat_rental_request_url %></h3>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>